import Vue from 'vue'
import { Button, Pagination, Search, Toast, Grid, GridItem, Icon, Col, Row, Tab, Tabs,Image as VanImage,
  Progress,Loading,Calendar,Uploader,List,Sticky,Switch,
  Panel,Cell, CellGroup,Divider,Tabbar, TabbarItem, Form,Picker,Field,Popup } from 'vant'

Vue.use(Pagination)
Vue.use(Button)
Vue.use(Search)
Vue.use(Toast)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Panel)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Divider)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Form)
Vue.use(Picker)
Vue.use(Field)
Vue.use(Popup)
Vue.use(Col)
Vue.use(Row)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(VanImage)
Vue.use(Progress)
Vue.use(Loading)
Vue.use(Calendar)
Vue.use(Uploader)
Vue.use(List)
Vue.use(Sticky)
Vue.use(Switch)