import Vue from 'vue'
import { Button, Pagination, Search, Toast, Grid, GridItem, Icon, Panel,Cell, CellGroup,Divider,Tabbar, TabbarItem, Form,Picker,Field,Popup } from 'vant'

Vue.use(Pagination)
Vue.use(Button)
Vue.use(Search)
Vue.use(Toast)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Panel)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Divider)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Form)
Vue.use(Picker)
Vue.use(Field)
Vue.use(Popup)